# Generated by Django 4.1.1 on 2022-09-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_fullname', models.CharField(max_length=100)),
                ('client_contact', models.CharField(max_length=10)),
                ('client_email', models.EmailField(max_length=100)),
                ('client_password', models.CharField(max_length=100)),
                ('client_photo', models.ImageField(null=True, upload_to='images/')),
                ('client_status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'db_table': 'client_details',
            },
        ),
    ]
