# Generated by Django 4.1.1 on 2022-09-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_video', models.FileField(null=True, upload_to='uploads/')),
                ('file_duration', models.DurationField()),
                ('file_upload_date', models.DateField(auto_now_add=True)),
                ('file_upload_time', models.TimeField(auto_now_add=True)),
                ('client_file_upload_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.clientmodel')),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
    ]
