# Generated by Django 4.1.1 on 2022-10-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_filesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='file_upload_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='file_upload_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
