# Generated by Django 4.1.1 on 2022-10-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_filesmodel_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesmodel',
            old_name='client_file_upload_id',
            new_name='video_uploader',
        ),
        migrations.AddField(
            model_name='filesmodel',
            name='file_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
