# Generated by Django 4.1.1 on 2022-10-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_remove_filesmodel_file_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesmodel',
            name='file_upload_date',
        ),
        migrations.RemoveField(
            model_name='filesmodel',
            name='file_upload_time',
        ),
        migrations.AddField(
            model_name='filesmodel',
            name='file_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filesmodel',
            name='file_message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
