# Generated by Django 4.1.1 on 2022-10-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_remove_filesmodel_file_upload_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesmodel',
            old_name='file_datetime',
            new_name='file_date',
        ),
    ]
