# Generated by Django 4.1.1 on 2022-10-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_rename_file_datetime_filesmodel_file_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='file_date',
            field=models.DateField(auto_now=True),
        ),
    ]
