# Generated by Django 4.1.1 on 2022-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_alter_filesmodel_file_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='file_status',
            field=models.CharField(default='pending', help_text='file_status', max_length=300),
        ),
    ]
