# Generated by Django 4.1.1 on 2022-10-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0011_filesmodel_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesmodel',
            name='file_transfer_status',
            field=models.CharField(default='pending', help_text='file_status', max_length=300),
        ),
        migrations.AlterField(
            model_name='filesmodel',
            name='file_message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
