# Generated by Django 4.1.1 on 2022-11-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0014_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
