# Generated by Django 4.1.1 on 2022-11-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0015_document_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocumentModel',
            fields=[
                ('upload_file', models.AutoField(primary_key=True, serialize=False)),
                ('upload_file_name', models.CharField(max_length=100)),
                ('uploaded_video_file', models.FileField(null=True, upload_to='uploads/')),
                ('file_uploaded_at', models.DateTimeField(auto_now=True)),
                ('upload_message', models.CharField(max_length=1000, null=True)),
                ('upload_file_status', models.CharField(default='pending', help_text='file_status', max_length=300)),
                ('upload_file_transfer_status', models.CharField(default='pending', help_text='file_transfer_status', max_length=300)),
                ('video_uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_details', to='clientapp.clientmodel')),
            ],
            options={
                'db_table': 'uploaded_files_details',
            },
        ),
        migrations.RemoveField(
            model_name='filesmodel',
            name='video_uploader',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='FilesModel',
        ),
    ]
