# Generated by Django 4.1.1 on 2022-11-05 10:01

import cloudstorage.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0016_uploaddocumentmodel_remove_filesmodel_video_uploader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('privateupload_file', models.AutoField(primary_key=True, serialize=False)),
                ('privateuploaded_at', models.DateTimeField(auto_now_add=True)),
                ('privateuploadname', models.CharField(max_length=100, null=True)),
                ('privateuploadfile', models.FileField(storage=cloudstorage.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('privateuploadmessage', models.CharField(max_length=1000, null=True)),
                ('privateclient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clientapp.clientmodel')),
            ],
            options={
                'db_table': 'apikey_uploaded_file_details',
            },
        ),
    ]
