# Generated by Django 4.1.1 on 2022-11-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0018_privatedocument_privateuploadfilestatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatedocument',
            old_name='privateuploadfile',
            new_name='uploaded_video_file',
        ),
    ]
