# Generated by Django 4.1.1 on 2022-11-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0020_rename_privateuploaded_at_privatedocument_file_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='client_photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
