# Generated by Django 4.1.1 on 2022-11-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0022_privatedocument_efs_file_privatedocument_s3_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatedocument',
            name='file_size',
            field=models.BigIntegerField(help_text='file_size', null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='file_type',
            field=models.CharField(help_text='file_type', max_length=300, null=True),
        ),
    ]
