# Generated by Django 4.1.1 on 2022-11-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0024_remove_privatedocument_efs_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatedocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='privatedocument',
            name='file_type',
        ),
    ]
