# Generated by Django 4.1.1 on 2022-11-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0025_remove_privatedocument_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatedocument',
            name='efs_file',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='privatedocument',
            name='s3_files',
            field=models.FloatField(null=True),
        ),
    ]
