# Generated by Django 4.1.1 on 2022-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0027_privatedocument_file_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatedocument',
            name='random_id',
            field=models.IntegerField(help_text='random_id', null=True),
        ),
    ]
