# Generated by Django 4.1.1 on 2022-11-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0031_privatedocument_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedocument',
            name='random_id',
            field=models.CharField(default='none', help_text='random_id', max_length=100, null=True),
        ),
    ]
